In [18]:
import numpy as np
import neuraltda.H_MDS as hmds
reload(hmds)

<module 'neuraltda.H_MDS' from 'neuraltda/H_MDS.py'>

In [65]:
n = 4
X = np.random.randn(n)
Y = np.random.randn(n)
mag = np.multiply(np.random.uniform(1, 4, size=n), np.abs(X+1j*Y))
X = np.divide(X, mag)
Y = np.divide(Y, mag)
D = 10*np.square(np.random.randn(n, n))
D = D - np.diag(np.diag(D))
w = np.ones((n, n))
wtot = 0.5*np.sum(np.sum(D))
w = np.power(D+np.diag(np.ones(n)), -1)/wtot
w = w - np.diag(np.diag(w))


In [66]:
w

array([[  0.00000000e+00,   1.19722876e-03,   1.80785336e-02,
          4.29140646e-03],
       [  1.92865745e-03,   0.00000000e+00,   1.34098777e-03,
          6.30622190e-04],
       [  6.21488877e+00,   1.37455263e-03,   0.00000000e+00,
          2.22735589e-03],
       [  3.84207729e-03,   5.76360033e-04,   3.19656408e-01,
          0.00000000e+00]])

In [ ]:
test = hmds.d_H

In [ ]:
test = hmds.mobius_xform(1+1j, X[1]+1j*Y[1], 1)

In [ ]:
test = hmds.get_distances(X, Y)

In [ ]:
test = hmds.E_x(X, Y, D, w)

In [ ]:
test = hmds.dE_dxa(D, w, X, Y, 0, 2)

In [ ]:
test

In [ ]:
hmds.ddH_dx1_1(X[1]+1j*Y[1], )

In [ ]:
X

In [ ]:
Y

In [ ]:
new = hmds.HMDS_update(D, w ,X, Y, 1, 0.1)

In [ ]:
new

In [67]:
eta = 0.2
eps = 1e-6
diffp = 1
E = 0
while diffp > eps:
    alpha = np.random.randint(len(X))
    new = hmds.HMDS_update(D, w, X, Y, alpha, eta)
    X[alpha] = np.real(new)
    Y[alpha] = np.imag(new)
    newE = hmds.E_x(X, Y, D, w)
    diffp = np.abs(E - newE)
    print(newE)
    E = newE

6.66880624189
6.65208537333
4.98142948083
3.82468538466
13.9506674963
13.9389571395
13.9389123141


In [63]:
pts = X+1j*Y
print(pts[0])
print(pts[2])
np.abs(pts[2])

(-0.511558608907-0.566558305484j)
(-0.624933648241-0.625728336653j)


0.88435174901994806

In [64]:
print(hmds.get_distances(X, Y))
print(D)

[[ 0.          6.00707554  0.82458487         nan]
 [ 6.00707554  0.          6.79009484         nan]
 [ 0.82458487  6.79009484  0.                 nan]
 [        nan         nan         nan  0.        ]]
[[  0.00000000e+00   1.99792060e+01   2.36499468e+00   1.53405143e+01]
 [  1.24060164e+01   0.00000000e+00   1.12511099e+01   2.35143965e-01]
 [  4.09661513e+01   2.14068472e-02   0.00000000e+00   1.43925895e+01]
 [  1.48917918e-01   2.48583390e+00   1.02837678e+00   0.00000000e+00]]


In [60]:
d = hmds.get_distances(X, Y)
diffmat = np.subtract(d, D)
diffmat = np.square(diffmat)

E = 0.5*np.einsum('ij,ij', w, diffmat)
print(diffmat)
print(E)
print(w)

[[  0.00000000e+00   7.28588910e+00   7.46655962e+00   5.19337594e+02]
 [  3.71283231e+02   0.00000000e+00   5.13445936e-04   1.19533145e+03]
 [  1.65740292e+01   2.21474796e+01   0.00000000e+00   4.60105647e+00]
 [  6.98843871e-01   7.39900884e+01   2.14208566e-01   0.00000000e+00]]
nan
[[        inf  0.00333894  0.00187583  0.00028126]
 [ 0.00960614         inf  0.00909526  0.00119533]
 [ 0.01287936  0.00291381         inf  0.01645859]
 [ 0.00637723  0.00450455  0.00106681         inf]]


In [ ]:
def func_to_min(X, D, Npts):
    
    x = X[0:Npts]
    y = X[Npts:]
    d = hmds.get_distances(x, y)
    diff = np.subtract(d, D)
    return np.sum(diff, axis=1)

In [ ]:
from scipy.optimize import leastsq

In [ ]:
x0 = np.hstack((X, Y))
x0 = np.transpose(x0)

In [ ]:

res = leastsq(func_to_min, x0, args=(D, n))