In [167]:
import numpy as np
import neuraltda.H_MDS as hmds
reload(hmds)

<module 'neuraltda.H_MDS' from 'neuraltda/H_MDS.py'>

In [168]:
n = 4
X = np.random.randn(n)
Y = np.random.randn(n)
mag = np.multiply(np.random.uniform(1, 4, size=n), np.abs(X+1j*Y))
X = np.divide(X, mag)
Y = np.divide(Y, mag)
D = 10*np.square(np.random.randn(n, n))
D = D - np.diag(np.diag(D))
w = np.ones((n, n))
wtot = 0.5*np.sum(np.sum(D))
w = np.power(D+np.diag(np.ones(n)), -1)/wtot
w = w - np.diag(np.diag(w))


In [66]:
w

array([[  0.00000000e+00,   1.19722876e-03,   1.80785336e-02,
          4.29140646e-03],
       [  1.92865745e-03,   0.00000000e+00,   1.34098777e-03,
          6.30622190e-04],
       [  6.21488877e+00,   1.37455263e-03,   0.00000000e+00,
          2.22735589e-03],
       [  3.84207729e-03,   5.76360033e-04,   3.19656408e-01,
          0.00000000e+00]])

In [ ]:
test = hmds.d_H

In [ ]:
test = hmds.mobius_xform(1+1j, X[1]+1j*Y[1], 1)

In [ ]:
test = hmds.get_distances(X, Y)

In [ ]:
test = hmds.E_x(X, Y, D, w)

In [ ]:
test = hmds.dE_dxa(D, w, X, Y, 0, 2)

In [ ]:
test

In [ ]:
hmds.ddH_dx1_1(X[1]+1j*Y[1], )

In [ ]:
X

In [ ]:
Y

In [ ]:
new = hmds.HMDS_update(D, w ,X, Y, 1, 0.1)

In [ ]:
new

In [170]:
eta = 0.1
eps = 1e-4
epsvec = np.ones(n)
diffp = 1
E = 0
X_s = X
Y_s = Y
lamm = 0.001*np.ones(n)
while any(epsvec > eps):
    alpha = np.random.randint(len(X))
    lam = lamm[alpha]
    E = hmds.E_x(X_s, Y_s, D, w)
    new = hmds.HMDS_update2(D, w, X_s, Y_s, alpha, eta, lam)
    X_s[alpha] = np.real(new)
    Y_s[alpha] = np.imag(new)
    newE = hmds.E_x(X_s, Y_s, D, w)
    if newE > E:
        lam = lam*10.0
        X_s = X
        Y_s = Y
    elif newE < E:
        lam = lam/10.0
    if lam > 1e4:
        lam = 1e4
    elif lam < 1e-4:
        lam = 1e-4
    lamm[alpha] = lam
    
    print('lam: {}'.format(lam))
    diffp = np.abs(newE-E)
    epsvec[alpha] = diffp
    print(newE)

delta mag: 2.6016855283
lam: 0.0001
0.584058382543
delta mag: 1.01872180253
lam: 0.01
0.676131991858
delta mag: 1.0163870878
lam: 0.001
0.583630822218
delta mag: 0.35484798088
lam: 0.01
0.584158339273
delta mag: 0.695401152978
lam: 0.0001
0.53420731023
delta mag: 0.994778139557
lam: 0.01
0.607048786609
delta mag: 0.384861599075
lam: 0.001
0.609867515718
delta mag: 1.20165442728
lam: 0.001
0.527385617156
delta mag: 2.37956813013
lam: 0.001
0.636444496903
delta mag: 1.10008837219
lam: 0.01
0.647382343043
delta mag: 0.536138471399
lam: 0.0001
0.597243672261
delta mag: 3.70102243937
lam: 0.001
0.575933337555
delta mag: 0.314421649358
lam: 0.1
0.576141335652
delta mag: 0.282743388121
lam: 1.0
0.576302542935
delta mag: 0.135162598837
lam: 0.01
0.576775378926
delta mag: 0.144028688071
lam: 0.1
0.577322489737
delta mag: 0.1485624438
lam: 1.0
0.577935052202
delta mag: 0.18870841017
lam: 10.0
0.578042714098
delta mag: 0.424299910164
lam: 0.0001
0.543668913499
delta mag: 0.765304792677
lam: 0.000

In [99]:

pts = X+1j*Y
print(pts[0])
print(pts[3])
np.abs(pts[3])

(nan+nan*j)
(-0.4071771736-0.404894816424j)


0.5742238788734455

In [172]:
print(hmds.get_distances(X_s, Y_s))
print(D)

[[ 0.          3.52812408  7.81488378  5.94202381]
 [ 3.52812408  0.          6.65759146  5.59163675]
 [ 7.81488378  6.65759146  0.          7.7535026 ]
 [ 5.94202381  5.59163675  7.7535026   0.        ]]
[[  0.           6.75505296   3.44124412   1.01019657]
 [ 23.09804752   0.           4.20835583   3.13886846]
 [  9.53867751  14.08503741   0.          26.9987807 ]
 [  0.48612112   8.73632758  12.43625715   0.        ]]


In [89]:
d = hmds.get_distances(X, Y)
diffmat = np.subtract(d, D)
diffmat = np.square(diffmat)

E = 0.5*np.einsum('ij,ij', w, diffmat)
print(diffmat)
print(E)
print(w)

[[  0.00000000e+00   7.39759875e-02   4.87134332e+00   2.81126433e-02]
 [  2.77464576e+02   0.00000000e+00   5.58443242e-01   3.68150155e+02]
 [  2.77148508e+01   3.29282995e+02   0.00000000e+00   2.07739598e-01]
 [  1.61322304e-01   1.95374039e-02   6.74004724e+00   0.00000000e+00]]
1.13375941223
[[  0.00000000e+00   6.60361676e-01   9.85421787e-03   8.82072078e+00]
 [  1.71032421e-03   0.00000000e+00   2.48084185e-02   1.50162201e-03]
 [  4.83562856e-03   1.56334026e-03   0.00000000e+00   2.59054145e-01]
 [  5.06972604e-02   5.57012031e+00   9.17498477e-03   0.00000000e+00]]


In [ ]:
def func_to_min(X, D, Npts):
    
    x = X[0:Npts]
    y = X[Npts:]
    d = hmds.get_distances(x, y)
    diff = np.subtract(d, D)
    return np.sum(diff, axis=1)

In [ ]:
from scipy.optimize import leastsq

In [ ]:
x0 = np.hstack((X, Y))
x0 = np.transpose(x0)

In [ ]:

res = leastsq(func_to_min, x0, args=(D, n))