In [17]:
import pickle
import numpy as np
import sys

In [15]:

fname = '/home/brad/krista/B1075/P01S03/oldPredictionResults/20160923T165344Z-25.0-4.0-masterResults.pkl-predictionAccuracy-ShuffledBettis'
with open(fname, 'rb') as f:
    test = pickle.load(f, encoding='bytes')
    
fname = '/home/brad/krista/B1075/P01S03/oldPredictionResults/20161005T012837Z-25.0-4.0-masterResults.pkl-predictionAccuracyShuff'
with open(fname, 'rb') as f:
    tests = pickle.load(f, encoding='bytes')

In [17]:
np.mean(test)

0.61822916666666672

In [13]:
tests

array([ 0.503125,  0.465625,  0.46875 ,  0.440625,  0.496875,  0.521875,
        0.559375,  0.528125,  0.55625 ,  0.446875,  0.49375 ,  0.50625 ,
        0.5     ,  0.575   ,  0.5375  ,  0.503125,  0.45    ,  0.5125  ,
        0.515625,  0.534375,  0.56875 ,  0.434375,  0.446875,  0.475   ,
        0.440625,  0.4375  ,  0.5375  ,  0.44375 ,  0.584375,  0.4125  ])

In [95]:
-

In [96]:
#get_faces(11, 4)
(N, nbits) = max_simp_to_binary([0, 1, 3, 8, 22, 81, 99, 104, 221])
%time simplicialChainGroups([(0,1,2,3), (0,1,4,5), (0,1,2,3,4,5,6,7,8,9,10)])

12
CPU times: user 36 ms, sys: 0 ns, total: 36 ms
Wall time: 37.2 ms


[[()],
 [(0,), (1,), (2,), (3,), (4,), (5,), (6,), (7,), (8,), (9,), (10,)],
 [(0, 1),
  (0, 2),
  (0, 3),
  (0, 4),
  (0, 5),
  (0, 6),
  (0, 7),
  (0, 8),
  (0, 9),
  (0, 10),
  (1, 2),
  (1, 3),
  (1, 4),
  (1, 5),
  (1, 6),
  (1, 7),
  (1, 8),
  (1, 9),
  (1, 10),
  (2, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (2, 7),
  (2, 8),
  (2, 9),
  (2, 10),
  (3, 4),
  (3, 5),
  (3, 6),
  (3, 7),
  (3, 8),
  (3, 9),
  (3, 10),
  (4, 5),
  (4, 6),
  (4, 7),
  (4, 8),
  (4, 9),
  (4, 10),
  (5, 6),
  (5, 7),
  (5, 8),
  (5, 9),
  (5, 10),
  (6, 7),
  (6, 8),
  (6, 9),
  (6, 10),
  (7, 8),
  (7, 9),
  (7, 10),
  (8, 9),
  (8, 10),
  (9, 10)],
 [(0, 1, 2),
  (0, 1, 3),
  (0, 1, 4),
  (0, 1, 5),
  (0, 1, 6),
  (0, 1, 7),
  (0, 1, 8),
  (0, 1, 9),
  (0, 1, 10),
  (0, 2, 3),
  (0, 2, 4),
  (0, 2, 5),
  (0, 2, 6),
  (0, 2, 7),
  (0, 2, 8),
  (0, 2, 9),
  (0, 2, 10),
  (0, 3, 4),
  (0, 3, 5),
  (0, 3, 6),
  (0, 3, 7),
  (0, 3, 8),
  (0, 3, 9),
  (0, 3, 10),
  (0, 4, 5),
  (0, 4, 6),
  (0, 4, 7),
  (0, 4,

In [3]:
import neuraltda.simpComp as sc

In [14]:
%time test = sc.simplicialChainGroups([(0,1,2,3), (0,1,4,5),  (5,6,7)])

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 351 µs


In [15]:
lap = sc.compute_laplacian(test, 2)
print(lap)

[[ 4.  0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  4.  1.  1.  0.  0.  0.  0.  0.]
 [ 1.  1.  4.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  4.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  4.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  3.]]


In [24]:
%time test = sc.simplicialChainGroups([(1,3,7, 110), (3,5,6,7), (0,1,2,3,4,5,6,7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)])

CPU times: user 15.8 s, sys: 104 ms, total: 15.9 s
Wall time: 15.9 s


In [11]:
%time test = sc.simplicialChainGroups([(0,1,2,3)])

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 358 µs


In [7]:
0.004*500


2.0

In [11]:
sc.boundaryOperator([1])

{(): 0}

In [18]:
sptimef = '/home/brad/spike_times.npy'
sptimes = np.load(sptimef)

In [21]:
sptimes.shape

(13403355, 1)