In [23]:
import numpy as np
from neuraltda import topology2 as tp2
from importlib import reload
reload(tp2)

<module 'neuraltda.topology2' from '/home/brad/code/NeuralTDA/neuraltda/topology2.py'>

In [24]:
# generate a poptens list
npoptens = 4
poptensshape = (3,5,1)
test_poptens = np.random.randint(2, size=poptensshape)
#poptens_list = [np.random.randint(2, size=poptensshape) for x in range(npoptens)]
poptens_list = npoptens*[test_poptens]
poptens_list_shuffled = tp2.shuffle_mask_within_stims(poptens_list, [np.arange(3)])
poptens_list_shuffled2 = tp2.shuffle_mask_across_stims(poptens_list, [np.arange(3)])

In [25]:
for x, y, z in zip(poptens_list, poptens_list_shuffled, poptens_list_shuffled2):
    print(x[:, :, 0])
    print(y[:, :, 0])
    print(z[:, :, 0])
    print(" ")

[[0 1 0 1 0]
 [1 0 0 0 0]
 [1 1 0 0 1]]
[[1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0.]]
[[0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 1.]]
 
[[0 1 0 1 0]
 [1 0 0 0 0]
 [1 1 0 0 1]]
[[1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1.]]
[[0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 1.]]
 
[[0 1 0 1 0]
 [1 0 0 0 0]
 [1 1 0 0 1]]
[[0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 1.]]
[[0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 1.]]
 
[[0 1 0 1 0]
 [1 0 0 0 0]
 [1 1 0 0 1]]
[[0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 1.]]
[[0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 1.]]
 
