In [15]:
import numpy as np
import networkx as nx
from scipy.integrate import odeint

In [107]:
N = 5
mat = np.abs(0.01*np.random.standard_normal([N, N]))

In [108]:
dg = nx.DiGraph(data=mat)

In [109]:
dg.get_edge_data(0,2)

{'weight': 0.005974789799994832}

In [110]:
alpha = 0.01
def graph_flow(A, t):
    A = np.reshape(A, [N, N])
    
    B = A - np.dot(A, np.dot(A.T, A))
    dA = alpha*np.multiply(A, B)
    dA = np.reshape(dA, N**2)
    return dA

def integrate_A(Ainit, tmax):
    t = np.arange(tmax)
    Ainit = np.reshape(Ainit, N**2)
    out = odeint(graph_flow, Ainit, t)
    return (out, t)

In [118]:
(Aout, t) = integrate_A(mat, 800/alpha)

In [119]:
Anew = Aout[-1, :]

In [98]:
Atraj = Aout[:, 4]

In [99]:
At

array([ 0.02148284,  0.02148724,  0.02149164, ...,  0.        ,
        0.        ,  0.        ])

In [121]:
Anew.shape = [N, N]
Ab = Anew + Anew.T
print(np.array_str(Ab, precision=2))

[[  1.27e-02   2.39e-03   1.01e+00   3.28e-03   3.84e-02]
 [  2.39e-03   2.54e-03   9.96e-04   2.97e-04   2.00e+00]
 [  1.01e+00   9.96e-04   5.76e-04   1.00e+00   1.45e-03]
 [  3.28e-03   2.97e-04   1.00e+00   5.94e-02   2.51e-02]
 [  3.84e-02   2.00e+00   1.45e-03   2.51e-02   2.91e-05]]
